package contextpack

import (
	"fmt"
	"strings"
	"testing"
)

func TestIsGoGeneratedFollowsGoGenerateMarkerRule(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		path   string
		header string
		want   bool
	}{
		{
			name: "standard marker before package",
			path: "internal/types/user.go",
			header: `// Copyright 2026
// Code generated by stringer. DO NOT EDIT.

package types
`,
			want: true,
		},
		{
			name: "marker after code ignored",
			path: "internal/types/user.go",
			header: `package types

// Code generated by stringer. DO NOT EDIT.
`,
		},
		{
			name: "go generate directive is not generated marker",
			path: "internal/types/user.go",
			header: `//go:generate stringer -type Kind
package types
`,
		},
		{
			name: "non go file ignored",
			path: "schema.sql",
			header: `-- Code generated by tool. DO NOT EDIT.
`,
		},
		{
			name: "generic marker ignored",
			path: "internal/types/user.go",
			header: `// Generated by stringer. DO NOT EDIT.
package types
`,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			if got := IsGoGenerated(tc.path, tc.header); got != tc.want {
				t.Fatalf("IsGoGenerated() = %t, want %t", got, tc.want)
			}
		})
	}
}

func TestBuildCollapsesLargeGeneratedGroupWithoutProjectRules(t *testing.T) {
	t.Parallel()

	files := make([]FileFact, 0, 502)
	for i := range 500 {
		files = append(files, FileFact{
			Path:    fmt.Sprintf("pkg/generated/type_%03d.go", i),
			Status:  "M",
			Adds:    10 + i%7,
			Deletes: 5 + i%3,
			Header: `// Code generated by test fixture. DO NOT EDIT.
package generated
`,
		})
	}
	files = append(files,
		FileFact{Path: "config.json", Status: "M", Adds: 2, Deletes: 1, Header: `{"generated": true}`},
		FileFact{Path: "docs/readme.md", Status: "M", Adds: 3, Deletes: 0, Header: "<!-- DO NOT EDIT -->"},
	)

	pack := Build(files, Options{})
	if pack.Overview.Files != 502 {
		t.Fatalf("files = %d", pack.Overview.Files)
	}
	if pack.Overview.GeneratedFiles != 500 {
		t.Fatalf("generated files = %d", pack.Overview.GeneratedFiles)
	}
	if len(pack.Groups) != 1 {
		t.Fatalf("groups = %#v", pack.Groups)
	}
	group := pack.Groups[0]
	if !group.Generated || group.GeneratedByRule != GoGeneratedRule {
		t.Fatalf("generated group = %#v", group)
	}
	if group.Count != 500 || group.Match != "pkg/generated/*.go" {
		t.Fatalf("group = %#v", group)
	}
	if len(group.Samples) != 3 || len(group.TopChurn) != 3 {
		t.Fatalf("samples/top churn = %#v / %#v", group.Samples, group.TopChurn)
	}
	if len(pack.Outliers) != 2 {
		t.Fatalf("outliers = %#v", pack.Outliers)
	}
	for _, group := range pack.Groups {
		if strings.Contains(group.Summary, "web/uc") || strings.Contains(group.Summary, "go_types_generator") {
			t.Fatalf("group summary contains project-specific logic: %s", group.Summary)
		}
	}
}
