package commitmsg

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/yusing/git-agent/internal/contextpack"
	"github.com/yusing/git-agent/internal/gitctx"
)

func TestValidateRejectsFencesAndAmendProcessPhrasing(t *testing.T) {
	t.Parallel()

	errs := Validate(ModeAmend, "Update parser\n\nThis amend also fixes docs.\n```")
	if len(errs) < 2 {
		t.Fatalf("expected multiple validation errors, got %v", errs)
	}
}

func TestPromptsNameRequiredScope(t *testing.T) {
	t.Parallel()

	if got := UserPrompt(ModeNormal, 30, 24); !containsAll(got, "Current limits: 30 total model steps, 24 total tool calls.", "staged diff", "git_staged_diff", "ignore unstaged", "task IDs", "cover every distinct staged-diff change cluster") {
		t.Fatalf("normal prompt missing staged scope: %s", got)
	}
	if got := SystemPrompt(ModeNormal); !containsAll(got, "staged paths", "authoritative scope", "distinct high-signal staged change cluster") {
		t.Fatalf("normal system prompt missing cluster coverage: %s", got)
	}
	if got := SystemPrompt(ModeNormal); !containsAll(got, "previous HEAD diff", "contrast", "avoid restating previous work") {
		t.Fatalf("normal system prompt missing previous-diff contrast guard: %s", got)
	}
	if got := SystemPrompt(ModeAmend); !containsAll(got, "final amended commit", "versus its parent", "one commit", "Do not narrate a delta or process") {
		t.Fatalf("amend prompt missing final commit scope: %s", got)
	}
	if got := UserPrompt(ModeAmend, 12, 9); !containsAll(got, "Current limits: 12 total model steps, 9 total tool calls.", "How to read the evidence", "authoritative", "do not dual-narrate", "tone / scope / task IDs") {
		t.Fatalf("amend user prompt missing evidence framing: %s", got)
	}
	if got := UserPrompt(ModePR, 12, 9); !containsAll(got, "Current limits: 12 total model steps, 9 total tool calls.", "squash merge commit message", "origin/HEAD", "git_pr_diff", "branch commits") {
		t.Fatalf("pr prompt missing branch scope: %s", got)
	}
}

func TestPreparedCommitPromptUsesStagedDiffAsAuthoritativeScope(t *testing.T) {
	t.Parallel()

	prepared := PreparedCommitContext{
		Mode:        ModeNormal,
		StagedPaths: []string{"internal/web/uc/phoneconfig/common.go", "internal/web/uc/schedtask/task.go"},
		StagedStats: []gitctx.FileStat{{Path: "internal/web/uc/schedtask/task.go", Adds: 6, Deletes: 1}},
		PreviousHeadPaths: []string{
			"tools/database/go_types_generator/main_test.go",
			"tools/database/go_types_generator/typedef.go.tmpl",
		},
		PreviousHeadStats:         []gitctx.FileStat{{Path: "tools/database/go_types_generator/typedef.go.tmpl", Adds: 42, Deletes: 1}},
		PreviousHeadDiff:          "diff --git a/tools/database/go_types_generator/typedef.go.tmpl b/tools/database/go_types_generator/typedef.go.tmpl\n+func (q {{$structName}}Query) By{{.FieldName}}Str(v string)",
		PreviousHeadDiffTruncated: true,
		Diff:                      "diff --git a/internal/web/uc/schedtask/task.go b/internal/web/uc/schedtask/task.go\n+json.Valid(task.Parameter)",
		DiffTruncated:             false,
	}
	got := UserPromptWithPreparedCommitContext(prepared, 30, 24)
	if !containsAll(got,
		"prepared_commit_context is authoritative",
		"staged_paths, staged_status, and staged_stats summarize",
		"cover every distinct staged-diff change cluster",
		"previous_head_paths, previous_head_stats, previous_head_diff, previous_head_summary, and previous_head_context_pack are contrast only",
		"rely on previous_head_paths/stats for contrast shape",
		"describe only the new staged delta",
		"do not copy phrasing from recent commits or previous_head_diff",
		"go_types_generator/typedef.go.tmpl",
		"internal/web/uc/schedtask/task.go",
		"json.Valid(task.Parameter)",
	) {
		t.Fatalf("prepared commit prompt missing staged authority framing:\n%s", got)
	}
	if !strings.Contains(got, `"diff_truncated": false`) {
		t.Fatalf("prepared commit prompt missing truncation signal:\n%s", got)
	}
}

func TestPreparedCommitPromptUsesContextPackForLargeGeneratedDiffs(t *testing.T) {
	t.Parallel()

	paths := make([]string, 0, 101)
	stats := make([]gitctx.FileStat, 0, 101)
	facts := make([]contextpack.FileFact, 0, 101)
	for i := range 101 {
		path := filepath.ToSlash(filepath.Join("pkg", "generated", fmt.Sprintf("type_%03d.go", i)))
		paths = append(paths, path)
		stats = append(stats, gitctx.FileStat{Path: path, Adds: 12, Deletes: 8})
		facts = append(facts, contextpack.FileFact{
			Path:    path,
			Status:  "M",
			Adds:    12,
			Deletes: 8,
			Header: `// Code generated by fixture. DO NOT EDIT.
package generated
`,
		})
	}
	rawDiff := strings.Repeat("diff --git a/pkg/generated/type.go b/pkg/generated/type.go\n+raw generated line\n", 700)
	prepared := PreparedCommitContext{
		Mode:          ModeNormal,
		StagedPaths:   paths,
		StagedStats:   stats,
		ContextPack:   contextpack.Build(facts, contextpack.Options{}),
		RecentCommits: []gitctx.CommitInfo{{Summary: "chore(types): regenerate generated outputs"}},
		Diff:          rawDiff,
		DiffTruncated: true,
	}

	got := UserPromptWithPreparedCommitContext(prepared, 30, 24)
	if !containsAll(got, "context_pack", "generated_files", "diff_ref", "prepared_commit_context.diff", "previous_head_context_pack", "go-generated-comment") {
		t.Fatalf("prompt missing compact context pack:\n%s", got)
	}
	if strings.Contains(got, "+raw generated line") {
		t.Fatalf("large raw diff leaked into compact prompt")
	}
}

func TestPreparedCommitPromptPreservesOutlierDiffForLargeGeneratedChanges(t *testing.T) {
	t.Parallel()

	repoDir := filepath.Join(t.TempDir(), "repo")
	initGitRepo(t, repoDir)
	writeFile(t, filepath.Join(repoDir, "README.md"), "base\n")
	runGit(t, repoDir, "add", "README.md")
	runGit(t, repoDir, "commit", "-m", "chore: base")

	for i := range 101 {
		path := filepath.Join(repoDir, "pkg", "generated", fmt.Sprintf("type_%03d.go", i))
		writeFile(t, path, generatedFixtureContent(i))
	}
	writeFile(t, filepath.Join(repoDir, "zz_feature", "feature.go"), `package feature

func FeatureFlag() bool {
	return true
}
`)
	runGit(t, repoDir, "add", ".")

	repo, err := gitctx.Open(repoDir)
	if err != nil {
		t.Fatal(err)
	}
	prepared, err := PrepareCommitContext(repo)
	if err != nil {
		t.Fatal(err)
	}
	if !contextpack.IsLargeGeneratedHeavy(prepared.ContextPack) {
		t.Fatalf("fixture did not build generated-heavy context pack: %#v", prepared.ContextPack.Overview)
	}
	if !prepared.DiffTruncated {
		t.Fatalf("fixture expected capped full diff")
	}
	if strings.Contains(prepared.Diff, "FeatureFlag") {
		t.Fatalf("fixture expected capped full diff to omit outlier:\n%s", prepared.Diff)
	}

	got := UserPromptWithPreparedCommitContext(prepared, 30, 24)
	if !containsAll(got,
		"outlier_diff",
		"diff --git a/zz_feature/feature.go b/zz_feature/feature.go",
		"+func FeatureFlag() bool",
		"context_pack",
		"generated_files",
	) {
		t.Fatalf("compact prompt missing outlier diff:\n%s", got)
	}
	if strings.Contains(got, "+\tGeneratedValue") {
		t.Fatalf("compact prompt leaked dominant generated diff:\n%s", got)
	}
}

func TestPreparedCommitTraceValueCompactsLargePreviousHeadLists(t *testing.T) {
	t.Parallel()

	stagedPaths := make([]string, 0, 101)
	stagedStats := make([]gitctx.FileStat, 0, 101)
	for i := range 101 {
		path := filepath.ToSlash(filepath.Join("cmd", "app", fmt.Sprintf("file_%03d.go", i)))
		stagedPaths = append(stagedPaths, path)
		stagedStats = append(stagedStats, gitctx.FileStat{Path: path, Adds: 1})
	}
	previousPaths := make([]string, 0, 101)
	previousStats := make([]gitctx.FileStat, 0, 101)
	facts := make([]contextpack.FileFact, 0, 101)
	for i := range 101 {
		path := filepath.ToSlash(filepath.Join("pkg", "generated", fmt.Sprintf("prev_%03d.go", i)))
		previousPaths = append(previousPaths, path)
		previousStats = append(previousStats, gitctx.FileStat{Path: path, Adds: 20, Deletes: 10})
		facts = append(facts, contextpack.FileFact{
			Path:    path,
			Status:  "changed",
			Adds:    20,
			Deletes: 10,
			Header: `// Code generated by fixture. DO NOT EDIT.
package generated
`,
		})
	}
	prepared := PreparedCommitContext{
		Mode:                    ModeNormal,
		StagedPaths:             stagedPaths,
		StagedStats:             stagedStats,
		PreviousHeadPaths:       previousPaths,
		PreviousHeadStats:       previousStats,
		PreviousHeadContextPack: contextpack.Build(facts, contextpack.Options{}),
		Diff:                    "diff --git a/cmd/app/main.go b/cmd/app/main.go\n+change",
	}

	got, ok := prepared.TraceValue().(map[string]any)
	if !ok {
		t.Fatalf("TraceValue type = %T", prepared.TraceValue())
	}
	if _, ok := got["previous_head_paths"]; ok {
		t.Fatalf("trace value leaked previous_head_paths")
	}
	if _, ok := got["previous_head_stats"]; ok {
		t.Fatalf("trace value leaked previous_head_stats")
	}
	if _, ok := got["staged_paths"]; ok {
		t.Fatalf("trace value leaked staged_paths")
	}
	if _, ok := got["staged_stats"]; ok {
		t.Fatalf("trace value leaked staged_stats")
	}
	data, err := json.Marshal(got)
	if err != nil {
		t.Fatal(err)
	}
	if !containsAll(string(data), "staged_summary", "previous_head_summary", "previous_head_context_pack", "generated_files") {
		t.Fatalf("trace value missing compact previous-head evidence: %#v", got)
	}
}

func TestPrepareCommitContextIncludesStagedSubmoduleCommits(t *testing.T) {
	t.Parallel()

	subDir := filepath.Join(t.TempDir(), "webui")
	initGitRepo(t, subDir)
	writeFile(t, filepath.Join(subDir, "ui.txt"), "v1\n")
	runGit(t, subDir, "add", "ui.txt")
	runGit(t, subDir, "commit", "-m", "feat(webui): initial")
	baseSHA := gitHead(t, subDir)
	writeFile(t, filepath.Join(subDir, "ui.txt"), "v2\n")
	runGit(t, subDir, "add", "ui.txt")
	runGit(t, subDir, "commit", "-m", "fix(webui): repair login redirect")
	writeFile(t, filepath.Join(subDir, "profile.txt"), "menu\n")
	runGit(t, subDir, "add", "profile.txt")
	runGit(t, subDir, "commit", "-m", "feat(webui): add profile menu")
	releaseSHA := gitHead(t, subDir)

	repoDir := filepath.Join(t.TempDir(), "parent")
	initGitRepo(t, repoDir)
	runGit(t, repoDir, "-c", "protocol.file.allow=always", "submodule", "add", subDir, "webui")
	runGit(t, filepath.Join(repoDir, "webui"), "checkout", baseSHA)
	runGit(t, repoDir, "add", ".")
	runGit(t, repoDir, "commit", "-m", "feat: add webui submodule")

	runGit(t, filepath.Join(repoDir, "webui"), "checkout", releaseSHA)
	runGit(t, repoDir, "add", "webui")

	repo, err := gitctx.Open(repoDir)
	if err != nil {
		t.Fatal(err)
	}
	prepared, err := PrepareCommitContext(repo)
	if err != nil {
		t.Fatal(err)
	}
	if len(prepared.StagedSubmodules) != 1 {
		t.Fatalf("staged submodules = %#v", prepared.StagedSubmodules)
	}
	submodule := prepared.StagedSubmodules[0]
	if submodule.Path != "webui" || submodule.OldSHA != baseSHA || submodule.NewSHA != releaseSHA {
		t.Fatalf("submodule = %#v", submodule)
	}
	if !submodule.LocalHistoryAvailable {
		t.Fatalf("expected local history, got %#v", submodule)
	}
	if !commitSummariesContain(submodule.Commits, "fix(webui): repair login redirect", "feat(webui): add profile menu") {
		t.Fatalf("submodule commits = %#v", submodule.Commits)
	}

	prompt := UserPromptWithPreparedCommitContext(prepared, 30, 24)
	if !containsAll(prompt,
		"staged_submodules",
		"fix(webui): repair login redirect",
		"feat(webui): add profile menu",
		"do not collapse them to a generic \"newer submodule refs\" message",
	) {
		t.Fatalf("prompt missing staged submodule evidence:\n%s", prompt)
	}
}

func TestShapeWrapsBodyAndKeepsSubject(t *testing.T) {
	t.Parallel()

	got := Shape("Add parser\n\n" + strings.Repeat("word ", 30))
	if !strings.HasPrefix(got, "Add parser\n\n") {
		t.Fatalf("missing subject/body split: %q", got)
	}
	for _, line := range strings.Split(got, "\n")[2:] {
		if len(line) > 72 {
			t.Fatalf("line too long: %d %q", len(line), line)
		}
	}
}

func TestShapeRepairsWrappedSubjectContinuation(t *testing.T) {
	t.Parallel()

	output := `refactor(uc): adopt typed query helpers across asterisk, IM and
phoneconfig (T46750)

Switch staged UC packages from model-based query building to typed
query helpers and generated accessors.`

	got := Shape(output)
	want := `refactor(uc): adopt typed query helpers across asterisk, IM and phoneconfig (T46750)

Switch staged UC packages from model-based query building to typed
query helpers and generated accessors.`
	if got != want {
		t.Fatalf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestPreserveTaskIDSuffixDoesNotLeaveWrappedSubjectShardInBody(t *testing.T) {
	t.Parallel()

	output := `refactor(uc): adopt typed query helpers across asterisk, IM and
phoneconfig

Switch staged UC packages from model-based query building to typed
query helpers and generated accessors.`

	shaped := Shape(output)
	got := PreserveTaskIDSuffix(shaped, []gitctx.CommitInfo{
		{Summary: "feat(typegen): keep generated Col field helpers when referenced (T46750)"},
	})
	want := `refactor(uc): adopt typed query helpers across asterisk, IM and phoneconfig (T46750)

Switch staged UC packages from model-based query building to typed
query helpers and generated accessors.`
	if got != want {
		t.Fatalf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestShapeDoesNotMergeLowercaseBodyForPlainSubject(t *testing.T) {
	t.Parallel()

	got := Shape(`Add parser
fixes lexer crashes when rules are empty`)
	want := `Add parser

fixes lexer crashes when rules are empty`
	if got != want {
		t.Fatalf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestShapeDoesNotMergeLowercaseBodyForShortConventionalSubject(t *testing.T) {
	t.Parallel()

	got := Shape(`fix(parser): handle empty rules
fixes lexer crashes when rules are empty`)
	want := `fix(parser): handle empty rules

fixes lexer crashes when rules are empty`
	if got != want {
		t.Fatalf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestPreserveTaskIDSuffixRestoresExactRecentSubjectMatch(t *testing.T) {
	t.Parallel()

	got := PreserveTaskIDSuffix(`fix(schedtask): log skipped duplicate task creation

Log duplicate task payloads before returning.`, []gitctx.CommitInfo{
		{Summary: "fix(schedtask): log skipped duplicate task creation (T46571)"},
	})
	if !strings.HasPrefix(got, "fix(schedtask): log skipped duplicate task creation (T46571)\n") {
		t.Fatalf("missing restored task ID suffix:\n%s", got)
	}
}

func TestPreserveTaskIDSuffixUsesLatestRecentTaskIDForNewSubject(t *testing.T) {
	t.Parallel()

	output := "feat(orm): preserve where insertion order and expose condition formatters"
	got := PreserveTaskIDSuffix(output, []gitctx.CommitInfo{
		{Summary: "feat(typegen): keep generated Col field helpers when referenced (T46750)"},
		{Summary: "feat(orm): expose query tx and cloned state accessors (T46571)"},
	})
	if want := output + " (T46750)"; got != want {
		t.Fatalf("task ID suffix = %q, want %q", got, want)
	}
}

func TestPreserveTaskIDSuffixRestoresDominantRecentTaskIDForSameScope(t *testing.T) {
	t.Parallel()

	got := PreserveTaskIDSuffix(`fix(uc): update nullable query filter call sites

Update UC callers to use the non-null convenience variants for nullable
string and int filters.`, []gitctx.CommitInfo{
		{Summary: "fix(uc): switch generated query call sites to typed By helpers (T46571)"},
		{Summary: "chore(types): regenerate db types (T46571)"},
		{Summary: "fix(typegen): preserve nullable values in generated By helpers (T46571)"},
		{Summary: "fix(schedtask): handle nullable data filters in task dedupe and cleanup (T46571)"},
	})
	if !strings.HasPrefix(got, "fix(uc): update nullable query filter call sites (T46571)\n") {
		t.Fatalf("missing dominant task ID suffix:\n%s", got)
	}
}

func TestPreserveTaskIDSuffixDoesNotUseOlderTaskIDWhenLatestHasNone(t *testing.T) {
	t.Parallel()

	output := "docs(readme): update install guide"
	got := PreserveTaskIDSuffix(output, []gitctx.CommitInfo{
		{Summary: "docs(readme): clarify install flow"},
		{Summary: "fix(uc): switch generated query call sites to typed By helpers (T46571)"},
		{Summary: "chore(types): regenerate db types (T46571)"},
	})
	if got != output {
		t.Fatalf("unexpected dominant task ID suffix restore: %q", got)
	}
}

func TestPromptsReflectExampleStyleExpectations(t *testing.T) {
	t.Parallel()

	if got := SystemPrompt(ModeNormal); !containsAll(got, "type, scope, and impact", "Body optional", "three short paragraphs") {
		t.Fatalf("normal system prompt missing style guidance: %s", got)
	}
	if got := UserPrompt(ModeNormal, 30, 24); !containsAll(got, "git_staged_status", "recent commits", "full staged diff") {
		t.Fatalf("normal user prompt missing structured context guidance: %s", got)
	}
	if got := UserPrompt(ModeAmend, 30, 24); !containsAll(got, "Previous HEAD message is reference only", "polish wording only") {
		t.Fatalf("amend prompt missing example-aligned reuse guidance: %s", got)
	}
	if got := SystemPrompt(ModePR); !containsAll(got, "current branch versus origin/HEAD", "one coherent commit", "squash merge") {
		t.Fatalf("pr system prompt missing squash framing: %s", got)
	}
}

func containsAll(text string, needles ...string) bool {
	for _, needle := range needles {
		if !strings.Contains(text, needle) {
			return false
		}
	}
	return true
}

func commitSummariesContain(commits []gitctx.CommitInfo, summaries ...string) bool {
	seen := map[string]bool{}
	for _, commit := range commits {
		seen[commit.Summary] = true
	}
	for _, summary := range summaries {
		if !seen[summary] {
			return false
		}
	}
	return true
}

func initGitRepo(t *testing.T, dir string) {
	t.Helper()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	runGit(t, dir, "init")
	runGit(t, dir, "config", "user.name", "Test User")
	runGit(t, dir, "config", "user.email", "test@example.com")
}

func runGit(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %v failed: %v\n%s", args, err, out)
	}
}

func gitHead(t *testing.T, dir string) string {
	t.Helper()
	cmd := exec.Command("git", "rev-parse", "HEAD")
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git rev-parse HEAD failed: %v\n%s", err, out)
	}
	return strings.TrimSpace(string(out))
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func generatedFixtureContent(index int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by fixture. DO NOT EDIT.\npackage generated\n\nconst (\n")
	for line := range 40 {
		fmt.Fprintf(&b, "\tGeneratedValue%03d%02d = %q\n", index, line, strings.Repeat("x", 40))
	}
	b.WriteString(")\n")
	return b.String()
}
